AWSTemplateFormatVersion: "2010-09-09"

Resources: 
  GameDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: "Games"
      AttributeDefinitions: 
        - 
          AttributeName: "id"
          AttributeType: "S"
        - 
          AttributeName: "status"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
        - 
          AttributeName: "status"
          KeyType: "RANGE"  
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5